config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    namespace :fulfillment do
      match 'dashboard' => 'dashboard#index'
      
      namespace :system_check do
        match 'index'
        match 'order_check'
        match 'ftp_check'
        post :generate_test_orders        
      end
      
      resource :settings

      resources :po_files do
        collection do
          delete :purge
          post :submit_all
        end
        member do
          post :submit
        end
      end

      resources :poa_files do
        collection do
          delete :purge
          post :load_files

        end

        member do
          post :import
        end
      end

      resources :asn_files do
        collection do
          delete :purge
          post :load_files
        end

        member do
          post :import
        end
      end

      resources :cdf_invoice_files do
        collection do
          delete :purge
          post :load_files
        end

        member do
          post :import
        end
      end
    end

    resources :orders do
      collection do
        get :test_orders
      end
      
      member do
        get :fulfillment
        post :duplicate
      end
    end


  end


end

app/models/po_file.rb
require 'net/ftp'

class PoFile < ActiveRecord::Base

  #noinspection RailsParamDefResolve
  has_many :orders, :autosave => true, :dependent => :nullify, :order => 'completed_at asc'

  #noinspection RailsParamDefResolve
  has_many :poa_files, :dependent => :destroy, :order => 'created_at asc'

  after_create :init_file_name

  before_destroy :delete_file

  attr_reader :count

  def read
    raise ArgumentError, "File not found: #{path}" unless has_file?

    File.read path
  end

  def has_file?
    self.persisted? ? File.exists?(path) : false
  end

  def initialize(attributes={})
    @count = init_counters
    super
  end


  # Generates a new PoFile for every order that is ready for
  # shipment
  def self.generate
    po_file = PoFile.new
    po_file.save!

    data = po_file.po00.cdf_record + Records::Base::LINE_TERMINATOR

    Order.needs_po.limit(25).each do |order|
      po_file.orders << order
      po = order.as_cdf(po_file.count[:total_records])
      data << po.to_s
      po_file.update_counters(order, po)
    end

    data << po_file.po90.cdf_record

    FileUtils.mkdir_p(File.dirname(po_file.path))
    File.open(po_file.path, 'w') { |f| f.write data }

    po_file.save!
    po_file
  end

  def self.prefix
    ''
  end

  def self.ext
    '.fbo'
  end

  def delete_file
    if self.persisted? && File.exists?(path)
      FileUtils.rm path
      return true
    end

    false
  end

  def init_file_name
    self.file_name = self.class.prefix + self.created_at.strftime("%y%m%d%H%M%S") + self.class.ext
    save!
  end


  def po00
    Records::Po::Po00.new(file_name)
  end

  def po90
    Records::Po::Po90.new(@count[:total_records], :name=>'Po90', :count => @count)
  end


  def update_counters(order, po)
    @count[:total_records] += po.count[:total]
    @count[:total_purchase_orders] += 1
    @count[:total_line_items] += order.line_items.count
    @count[:total_units] += order.total_quantity

    (0..8).each { |i| @count[i.to_s] = po.count[i.to_s] }

  end

  def path
    raise Cdf::IllegalStateError, "Can't get path until PoFile has been saved" unless persisted?

    "#{CdfConfig::data_lib_out_root(self.created_at.strftime("%Y"))}/#{file_name}"
  end

  def put
    raise ArgumentError, "File not found: #{path}" unless File.exists?(path)

    return self.submitted_at if self.submitted?

    client = CdfFtpClient.new

    puts client.to_yaml

    list = []
    client.connect do |ftp|
      ftp.chdir 'incoming'
      ftp.put File.new(path)
      list = ftp.list
    end
    
    puts list.to_yaml

    self.submitted_at = Time.now
    self.save!
    self.submitted_at
  end
  
  # Returns true if already submitted
  def submitted?
    !self.submitted_at.nil?
  end
  
  # Returns PoFiles that have not been submitted
  def self.not_submitted
    where(:submitted_at => nil)
  end

  private
  def init_counters
    count = {
        :total_records => 2, # one for the header and one for the first order
        :total_purchase_orders => 0,
        :total_line_items => 0,
        :total_units => 0
    }

    for i in 0..8 do
      count[i.to_s] = 0
    end
    count
  end


end

app/controllers/admin/fulfillment/po_files_controller.rb
class Admin::Fulfillment::PoFilesController < Admin::ResourceController

  def create
    if Order.needs_po.count == 0
      flash[:notice] = 'No Orders need POs'
      return redirect_to location_after_save
    end

    @object = PoFile.generate

    flash[:notice] = flash_message_for(@object, :successfully_created)
    respond_with(@object) do |format|
      format.html { redirect_to location_after_save }
      format.js { render :layout => false }
    end
  end
  
  def submit
    @po_file = PoFile.find_by_id params[:id]
    @po_file.put
    flash[:notice] = "Submitted PO File #{@po_file.file_name}"
    redirect_to :action => :show
  end

  def submit_all
    @count = PoFile.not_submitted.count
    PoFile.not_submitted.each {|po_file| po_file.put}
    title = @count == 1 ? t('po_file') : t('po_file').pluralize
    flash[:notice] = "Submitted #{@count} #{t('po_file')}"
    redirect_to :action => :index    
  end
  
  
  def show
    begin
      @data = @po_file.read
    rescue Exception => e
      flash[:error] = e.message
    end
  end

  def index
    params[:search] ||= {}
    @search = PoFile.metasearch(params[:search], :distinct => true)

    if !params[:search][:created_at_greater_than].blank?
      params[:search][:created_at_greater_than] = Time.zone.parse(params[:search][:created_at_greater_than]).beginning_of_day rescue ""
    end

    if !params[:search][:created_at_less_than].blank?
      params[:search][:created_at_less_than] = Time.zone.parse(params[:search][:created_at_less_than]).end_of_day rescue ""
    end

    @po_files = PoFile.metasearch(params[:search]).order('created_at desc').group('po_files.file_name').paginate(
        :per_page => Cdf::Config[:po_files_per_page],
        :page => params[:page])

    respond_with @po_files
  end


    # Deletes all PoFiles
  def purge
    count = PoFile.count
    Order.update_all('po_file_id = NULL', 'po_file_id IS NOT NULL')
    PoFile.delete_all
    flash[:notice] = "Deleted #{count} PoFiles"

    redirect_to location_after_save
  end

  def location_after_save
    admin_fulfillment_po_files_path
  end

end

app/controllers/admin/po_files_controller.rb
class Admin::PoFilesController < Admin::ResourceController


  def create
    @object = PoFile.generate

    flash[:notice] = flash_message_for(@object, :successfully_created)
    respond_with(@object) do |format|
      format.html { redirect_to location_after_save }
      format.js { render :layout => false }
    end
  end

  def show
    begin
      @po_file.load_file
      @data = @po_file.data
    rescue Exception => e
      flash[:error] = e.message
    end
  end

  def index
    params[:search] ||= {}
    @search = PoFile.metasearch(params[:search], :distinct => true)

    if !params[:search][:created_at_greater_than].blank?
      params[:search][:created_at_greater_than] = Time.zone.parse(params[:search][:created_at_greater_than]).beginning_of_day rescue ""
    end

    if !params[:search][:created_at_less_than].blank?
      params[:search][:created_at_less_than] = Time.zone.parse(params[:search][:created_at_less_than]).end_of_day rescue ""
    end

    @po_files = PoFile.metasearch(params[:search]).group('po_files.file_name').paginate(:per_page => Spree::Config[:po_files_per_page],
                                                            :page => params[:page])

    respond_with @po_files
  end


    # Deletes all PoFiles
  def purge
    count = PoFile.count
    PoFile.find(:all).each { |f| f.destroy }
    flash[:notice] = "Deleted #{count} PoFiles"

    redirect_to location_after_save
  end

end

app/views/admin/po_files/_po_file.html.haml
%tr
  %td
    = link_to po_file.file_name, admin_po_file_path(po_file)
  %td
    = po_file.orders.count
  %td
    = time_ago_in_words po_file.created_at
    ago

app/views/admin/po_files/index.html.haml
= render :partial => 'admin/shared/fulfillment_sub_menu'

%div.admin_buttons
  = form_tag(admin_po_files_path) do |f|
    %div
      = button t('create_po_file'), 'add'
    - if @po_files.length >0
      %div
        = link_to t('destroy_all_po_files'), purge_admin_po_files_path, :method => :delete

%h1 PO Files
%div
  %table.index
    %thead
      %tr
        %th
          = sort_link @search, :file_name, t('file_name')
        %th
          = t('record_count')
        %th
          = sort_link @search, :created_at, t('created_at')
    %tbody
      = render @po_files

= will_paginate(@po_files, :previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;")


- content_for :sidebar do
  .box
    %h3
      = t(:search)
    = form_for [:admin, @search] do |f|
      - locals = {:f => f}
      = hook :admin_po_files_index_search, locals do
        %label
          = t('date_range')

        .yui-g.date-range-filter
          .yui-u.sub-field.first
            = f.spree_date_picker :created_at_greater_than
            %label.sub
              = t("start")

          .yui-u.sub-field
            = f.spree_date_picker :created_at_less_than
            %label
              = t("stop")
        %label
          = t 'order_number'
        %br
        = f.text_field :orders_number_starts_with, :size=>25

      = hook :admin_orders_index_search_buttons, locals do
        %p
          = button t("search")

app/views/admin/po_files/show.html.haml
= render :partial => 'admin/shared/fulfillment_sub_menu'

%div.admin_buttons
  %div #{button_link_to t('back'), admin_po_files_path, :icon => '16x16/8'}

%h1 PO Files

%h2 #{@po_file.file_name}

%p Created at #{@po_file.created_at.strftime("%m-%d-%y %h:%M")}
%div.field_pair
  %legend
    = t('file_path')
  = @po_file.path


%h2 Contents
%div.contents
  - if @po_file.data
    %pre #{@po_file.data}
  - else
    &mdash;

- content_for :sidebar do
  .box
    %h3
      #{@po_file.orders.count} Orders
    %table
      %thead
        %tr
          %th ID
          %th Completed Date
      %tbody
      - for order in @po_file.orders do
        %tr
          %td
            = link_to order.number, admin_order_path(order)
          %td
            = order.completed_at.strftime("%m-%d-%y")