config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    namespace :fulfillment do
      match 'dashboard' => 'dashboard#index'
      
      namespace :system_check do
        match 'index'
        match 'order_check'
        match 'ftp_check'
        post :generate_test_orders        
      end
      
      resource :settings

      resources :po_files do
        collection do
          delete :purge
          post :submit_all
        end
        member do
          post :submit
        end
      end

      resources :poa_files do
        collection do
          delete :purge
          post :load_files

        end

        member do
          post :import
        end
      end

      resources :asn_files do
        collection do
          delete :purge
          post :load_files
        end

        member do
          post :import
        end
      end

      resources :cdf_invoice_files do
        collection do
          delete :purge
          post :load_files
        end

        member do
          post :import
        end
      end
    end

    resources :orders do
      collection do
        get :test_orders
      end
      
      member do
        get :fulfillment
        post :duplicate
      end
    end


  end


end

app/views/admin/orders/_asn_shipment.html.haml
%table
  %thead
    %tr
      %th #{t 'file_name'}
      %th #{t 'status'}
      %th #{t 'freight_charge'}
      %th #{t 'amount'}
      %th #{t 'subtotal'}
      %th #{t 'total'}
      %th #{t 'sales_tax'}
      %th #{t 'ship_date'}
      %th #{t 'item_count'}
      %th #{t 'shipping_and_handling'}
  %tbody
    - for asn_shipment in asn_shipments do
      %tr
        %td #{asn_shipment.asn_file.file_name}
        %td #{asn_shipment.asn_order_status.description}
        %td
          = number_to_currency asn_shipment.freight_charge
        %td
          = number_to_currency asn_shipment.order_discount_amount
        %td 
          = number_to_currency asn_shipment.order_subtotal
        %td
          = number_to_currency asn_shipment.order_total
        %td
          = number_to_currency asn_shipment.sales_tax
        %td #{asn_shipment.shipment_date.strftime("%m/%d/%Y")}
        %td #{asn_shipment.total_item_detail_count}
        %td
          = number_to_currency asn_shipment.shipping_and_handling

app/views/admin/orders/_import_file.html.haml
%h3 #{t("#{type}_files")}
%table
  %thead
    %tr
      %th
        = t 'file_name'
      %th
        = t 'imported_at'
  %tbody
  - for import_file in @order.send("#{type}_files".to_sym) do
    %tr
      %td
        = link_to import_file.file_name, send("admin_fulfillment_#{type}_file_path".to_sym, import_file)
      %td
        = import_file.created_at.strftime("%m/%d/%y %H:%M")

app/views/admin/orders/fulfillment.html.haml
= render 'admin/shared/order_tabs', :current => "Fulfillment"

%h2 #{t("fulfillment")}

%h3 #{t("po_files")}
%div
  - if @order.po_file
    %div
      %strong #{t 'file_name'}:
      = link_to @order.po_file.file_name, admin_fulfillment_po_file_path(@order.po_file)
    %div
      %strong #{t 'date'}:
      = @order.po_file.created_at.strftime("%m-%d-%y %H:%M")
  - else
    &mdash;

= render 'import_file', :type => "poa"

= render 'import_file', :type => "asn"

%h3 #{t 'asn_shipments'}
= render 'asn_shipment', :asn_shipments => @order.asn_shipments

- @order.asn_shipment_details.each do |asn_shipment_detail|
  = asn_shipment_detail.to_yaml

= render 'import_file', :type => 'cdf_invoice'

app/views/admin/orders/index.html.haml
%div{:class=>'toolbar order-links'}
  = button_link_to t("new_order"), new_admin_order_url, :icon => 'add', :id => 'admin_new_order'

= render :partial => 'admin/shared/order_sub_menu'

%h1 #{t("listing_orders")}

%table#listing_orders.index
  %thead
    %tr
      = hook :admin_orders_index_headers do
        %th #{sort_link @search, :completed_at, t("completed_or_created_at")}
        %th #{sort_link @search, :number, t("order_number")}
        %th #{sort_link @search, :order_type, t("order_type")}
        %th #{t("order_name")}
        %th #{sort_link @search, :state, t("status")}
        %th #{sort_link @search, :payment_state, t("payment_state")}
        %th #{ sort_link @search, :shipment_state, t("shipment_state")}
        %th #{ sort_link @search, :email, t("customer")}
        %th #{sort_link @search, :total, t("total")}
        %th 
          = hook :admin_orders_index_header_actions
  %tbody
    - @orders.each do |order| 
      - @class = order.order_type || :live
        
      %tr{:class => @class}
        - locals = {:order => order}
        = hook :admin_orders_index_rows, locals do
          %td #{(@show_only_completed ? order.completed_at : order.created_at).to_date}
          %td #{link_to order.number, admin_order_path(order)}
          %td #{t("order_type.#{order.order_type.downcase}")}
          %td #{order.order_name}
          %td #{t("order_state.#{order.state.downcase}")}
          %td #{link_to t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state}
          %td #{link_to t("shipment_states.#{order.shipment_state}"), admin_order_shipments_path(order) if order.shipment_state}
          %td #{order.email}
          %td #{number_to_currency order.total}
          %td.actions
            = hook :admin_orders_index_row_actions, locals do
              = link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}"

= will_paginate(@orders, :previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;")

= content_for :sidebar do 
  %div.box
  %h3 #{t(:search)}
  = form_for [:admin, @search] do |f| 
    - locals = {:f => f} 
    = hook :admin_orders_index_search, locals do 
      %label #{ t("date_range")}
      %br
      %div{:class=> "yui-g date-range-filter"}
        %div{:class => "yui-u sub-field first"}
          = f.spree_date_picker :created_at_greater_than 
          %br
          %label.sub #{ t("start") }
        
        %div{:class => "yui-u sub-field"}
          = f.spree_date_picker :created_at_less_than 
          %br
          %label #{t("stop")}
        
      %p
        %label #{ t("status") }
        %br
        = f.select :state_equals, Order.state_machines[:state].states.collect {|s| [t("order_state.#{s.name}"), s.value]}, {:include_blank => true}

      %p
        %label #{ t 'order_number'}
        %br
        = f.text_field :number_like, :size=>25 

      %p
        %label #{ t 'email'}
        %br
        = f.text_field :email_like, :size=>25 
      
      %p
        %label #{ t 'first_name_begins_with'}
        %br
          = f.text_field :bill_address_firstname_starts_with, :size=>25 
      
      %p
        %label #{ t 'last_name_begins_with'}
        %br
        = f.text_field :bill_address_lastname_starts_with, :size=>25 
        
      %p
        = f.check_box :completed_at_is_not_null, {:checked => @show_only_completed}, "1", "" 
        %label #{ t("show_only_complete_orders")}

      %p
        %label #{ t("order_type")}
        = f.select :order_type_equals, Order::TYPES.collect {|t| [t("order_type.#{t}"), t]}, {:include_blank => true}
        
    = hook :admin_orders_index_search_buttons, locals do 
      %p #{ button t("search") }
     