config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    namespace :fulfillment do
      match 'dashboard' => 'dashboard#index'
      
      namespace :system_check do
        match 'index'
        match 'order_check'
        match 'ftp_check'
        post :generate_test_orders        
      end
      
      resource :settings

      resources :po_files do
        collection do
          delete :purge
          post :submit_all
        end
        member do
          post :submit
        end
      end

      resources :poa_files do
        collection do
          delete :purge
          post :load_files

        end

        member do
          post :import
        end
      end

      resources :asn_files do
        collection do
          delete :purge
          post :load_files
        end

        member do
          post :import
        end
      end

      resources :cdf_invoice_files do
        collection do
          delete :purge
          post :load_files
        end

        member do
          post :import
        end
      end
    end

    resources :orders do
      collection do
        get :test_orders
      end
      
      member do
        get :fulfillment
        post :duplicate
      end
    end


  end


end

app/controllers/admin/fulfillment/asn_files_controller.rb
class Admin::Fulfillment::AsnFilesController < Admin::Fulfillment::ImportController



end

app/controllers/admin/fulfillment/cdf_invoice_files_controller.rb
class Admin::Fulfillment::CdfInvoiceFilesController < Admin::Fulfillment::ImportController



end

app/controllers/admin/fulfillment/dashboard_controller.rb
class Admin::Fulfillment::DashboardController < Admin::BaseController
  respond_to :html, :xml, :json

  def index
    @needs_po_count = Order.needs_po.count
    @submit_po_count = PoFile.not_submitted.count
    @po_files = PoFile.find(:all)
    respond_with @po_files
  end

end

app/controllers/admin/fulfillment/import_controller.rb
class Admin::Fulfillment::ImportController < Admin::ResourceController
  
  helper :data_view

  def create
    #begin
      files = model_class.download
      flash[:notice] = "#{files.count} files downloaded."
    #rescue => e
    #  flash[:error] = "Error downloading #{model_class}: #{e.message}, #{e.backtrace}"
    #end
    respond_with(@object) do |format|
      format.html { redirect_to polymorphic_url([:admin, :fulfillment, model_class]) }
      format.js { render :layout => false }
    end
  end

  def index
    @downloadable = model_class.remote_files
    
    params[:search] ||= {}
    @search = model_class.metasearch(params[:search], :distinct => true)

    if !params[:search][:created_at_greater_than].blank?
      params[:search][:created_at_greater_than] = Time.zone.parse(params[:search][:created_at_greater_than]).beginning_of_day rescue ""
    end

    if !params[:search][:created_at_less_than].blank?
      params[:search][:created_at_less_than] = Time.zone.parse(params[:search][:created_at_less_than]).end_of_day rescue ""
    end

    @collection = model_class.metasearch(params[:search]).order('created_at desc').group("#{object_name}s.file_name").paginate(
        :per_page => Cdf::Config["#{object_name}s_per_page"],
        :page => params[:page])

    respond_with @collection
  end

  # Import files
  def import
    begin
      result = @object.import!
      flash[:notice] = "Imported #{@object.file_name}."

    rescue => e
      flash[:error] = "#{e.message}"


    end
    respond_with(@object) do |format|
      format.html { redirect_to polymorphic_url([:admin, :fulfillment, object_name]) }
      format.js { render :layout => false }
    end

  rescue Exception => e
    flash[:error] = "Failed to import #{@object.file_name}. #{e.message}"
    logger.error e.backtrace
    raise e
  end


end

def location_after_save
  polymorphic_url(@object, :action => 'admin_fulfillment')
end

# Adds any files that are in the archive/in directory
# which are not yet added
# POST
def load_files
  count = 0

  model_class.files.each do |f|
    file_name = File.basename(f)

    next if model_class.find_by_file_name(file_name)

    model_class.create(:file_name => file_name)
    count += 1
  end

  flash[:notice] = "Loaded #{count} files."

  respond_to do |format|
    format.html { redirect_to send("admin_fulfillment_#{object_name}s_path") }
    format.js { render :layout => false }
  end
end

app/controllers/admin/fulfillment/po_files_controller.rb
class Admin::Fulfillment::PoFilesController < Admin::ResourceController

  def create
    if Order.needs_po.count == 0
      flash[:notice] = 'No Orders need POs'
      return redirect_to location_after_save
    end

    @object = PoFile.generate

    flash[:notice] = flash_message_for(@object, :successfully_created)
    respond_with(@object) do |format|
      format.html { redirect_to location_after_save }
      format.js { render :layout => false }
    end
  end
  
  def submit
    @po_file = PoFile.find_by_id params[:id]
    @po_file.put
    flash[:notice] = "Submitted PO File #{@po_file.file_name}"
    redirect_to :action => :show
  end

  def submit_all
    @count = PoFile.not_submitted.count
    PoFile.not_submitted.each {|po_file| po_file.put}
    title = @count == 1 ? t('po_file') : t('po_file').pluralize
    flash[:notice] = "Submitted #{@count} #{t('po_file')}"
    redirect_to :action => :index    
  end
  
  
  def show
    begin
      @data = @po_file.read
    rescue Exception => e
      flash[:error] = e.message
    end
  end

  def index
    params[:search] ||= {}
    @search = PoFile.metasearch(params[:search], :distinct => true)

    if !params[:search][:created_at_greater_than].blank?
      params[:search][:created_at_greater_than] = Time.zone.parse(params[:search][:created_at_greater_than]).beginning_of_day rescue ""
    end

    if !params[:search][:created_at_less_than].blank?
      params[:search][:created_at_less_than] = Time.zone.parse(params[:search][:created_at_less_than]).end_of_day rescue ""
    end

    @po_files = PoFile.metasearch(params[:search]).order('created_at desc').group('po_files.file_name').paginate(
        :per_page => Cdf::Config[:po_files_per_page],
        :page => params[:page])

    respond_with @po_files
  end


    # Deletes all PoFiles
  def purge
    count = PoFile.count
    Order.update_all('po_file_id = NULL', 'po_file_id IS NOT NULL')
    PoFile.delete_all
    flash[:notice] = "Deleted #{count} PoFiles"

    redirect_to location_after_save
  end

  def location_after_save
    admin_fulfillment_po_files_path
  end

end

app/controllers/admin/fulfillment/poa_files_controller.rb
class Admin::Fulfillment::PoaFilesController < Admin::Fulfillment::ImportController



end

app/controllers/admin/fulfillment/settings_controller.rb
class Admin::Fulfillment::SettingsController < Admin::BaseController

  def update
    begin
      Cdf::Config.set(params[:preferences]) if Cdf::Config.instance
    rescue => e
      logger.error e.message
      raise e
    end

    respond_to do |format|
      format.html {
        redirect_to admin_fulfillment_settings_path
      }
    end
  end

end

app/controllers/admin/fulfillment/system_check_controller.rb
class Admin::Fulfillment::SystemCheckController < Admin::BaseController
  respond_to :html, :xml, :json

  def index
  end

  def order_check
    @scenarios = Cdf::OrderBuilder::SCENARIOS
  end

  
  # POST /admin/orders
  # Creates a new set of orders for Fulfillment testing
  def generate_test_orders
    if params[:scenarios].empty?
      flash[:error] = "No orders created"
    else
      @orders = Cdf::OrderBuilder.create_for_scenarios params[:scenarios]
      flash[:notice] = "Created #{@orders.count} test orders"      
    end
    
    redirect_to :action => :order_check
  end
  
  def ftp_check
    client = CdfFtpClient.new({:keep_alive => true})
    @valid_server = client.valid_server?
    @valid_credentials = client.valid_credentials?
    if @valid_credentials
      @outgoing_files = client.outgoing_files
      @test_files = client.test_files
      @archive_files = client.archive_files
      @incoming_files = client.archive_files
    end
    client.close
    

  end

end

app/controllers/admin/fulfillment_controller.rb
class Admin::FulfillmentController < Admin::BaseController
  respond_to :html, :xml, :json

  def index
    @needs_po_count = Order.needs_po.count
    @po_files = PoFile.find(:all)
    respond_with @po_files
  end

end

app/views/admin/fulfillment/system_check/ftp_check.html.haml
= render :partial => 'admin/shared/system_check_menu'

%h1 #{t 'ftp_check'}

%div.settings
  %h2 Cdf Settings [#{link_to 'edit', admin_fulfillment_settings_path}]
  %ul
    %li 
      ftp server: #{Cdf::Config[:cdf_ftp_server]}
      - if @valid_server
        %span.valid [VALID]
      - else
        %span.invalid [INVALID]      
    %li ftp user: #{Cdf::Config[:cdf_ftp_user]}
    %li ftp pwd: #{Cdf::Config[:cdf_ftp_password]}
    %li 
      ftp credentials:
      - if @valid_credentials
        %span.valid [VALID]
      - else
        %span.invalid [INVALID]      
    %li ship to account: #{Cdf::Config[:cdf_ship_to_account]}
    %li ship to pwd: #{Cdf::Config[:cdf_ship_to_password]}
    %li bill to account: #{Cdf::Config[:cdf_bill_to_account]}

%div.remote_files
  %h2 Remote Files
  - if @valid_credentials
    - %w(incoming outgoing test archive).each do |dir|
      %h3 #{dir}
      %ul
        - instance_variable_get("@#{dir}_files").each do |file|
          %li #{file} 
  - else
    FTP credentials not valid

app/views/admin/fulfillment/system_check/generate_test_order.html.haml
= render :partial => 'admin/shared/system_check_menu'

= form_tag admin_fulfillment_system_check_generate_test_orders_path, :method => :post do

  %div.scenarios
    %h1 Select One or More Scenarios
    - @scenarios.each do |scenario|
      - field = "scenarios[]"
      %div{:class => field}
        = check_box_tag(field, scenario[:id], false, {'id' => "scenario_#{scenario[:id]}"})
        = label_tag(field, scenario[:name], :for => "scenario_#{scenario[:id]}")
  %div #{submit_tag 'Generate Test Orders'}

app/views/admin/fulfillment/system_check/index.html.haml
= render :partial => 'admin/shared/fulfillment_sub_menu'

%h1 #{t 'system_check'}

%table.index
  %thead
    %tr
      %th #{t 'system'}
      %th #{t 'description'}
  %tbody
    = hook :admin_system_check_menu do
      - %w{order_check ftp_check}.each do |key|
        %tr
          %td #{link_to t(key), send("admin_fulfillment_system_check_#{key}_path")}
          %td #{t "#{key}_description"}

app/views/admin/fulfillment/system_check/order_check.html.haml
= render :partial => 'admin/shared/system_check_menu'


= form_tag admin_fulfillment_system_check_generate_test_orders_path, :method => :post do

  %div.scenarios
    %h1 Select One or More Scenarios
    - @scenarios.each do |scenario|
      - field = "scenarios[]"
      %div{:class => field}
      
        = check_box_tag(field, scenario[:id], false, {'id' => "scenario_#{scenario[:id]}"})
        = label_tag(field, scenario[:name], :for => "scenario_#{scenario[:id]}")
  %div #{button t('generate_test_orders')}